# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzUwM2ViOGI2NWIyNzQxYWU3NjFmNjFkZWE1NzNhOTQ2NTlmNTViOGFmNjM2ZWEwNGUxZTkwYzNjMjIxNmUyZGY5NmE3ZDZmZDRjZWQxZTcxYzU4MDAxYTc1MzkzODVkYWViNzY3YTZhNmFiNWFiYzcwYjk4NjM2MWRiMzE2MmM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
